version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 
    volumes:
      - .:/code
      - sqlite_db:/code/db.sqlite3
    ports:
      - "8000:8000"

volumes:
  sqlite_db:
