# Generated by Django 5.0.6 on 2024-05-29 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='question',
        ),
    ]
