# Generated by Django 5.0.4 on 2024-06-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_solution_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='likes',
            field=models.ManyToManyField(related_name='post', to='forum.question'),
        ),
    ]
