# Generated by Django 5.0.6 on 2024-06-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_question_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
