# Generated by Django 5.0.6 on 2024-06-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_remove_question_likes_question_likes'),
        ('forum', '0010_solution_dislikes_alter_solution_likes'),
    ]

    operations = [
    ]
