# Generated by Django 5.0.6 on 2024-06-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_merge_20240604_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
    ]
