# Generated by Django 5.0.6 on 2024-06-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_uploaded/'),
        ),
    ]
