# Generated by Django 5.0.6 on 2024-06-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_alter_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_uploaded_sol/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(error_messages={'required': '*required'}, max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(error_messages={'required': '*required'}, max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(error_messages={'required': '*required'}, max_length=50),
        ),
    ]
